apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-world
spec:
  selector:
    matchLabels:
      app: node-hello-world
  template:
    metadata:
      labels:
        app: node-hello-world
    spec:
      containers:
      - name: node-hello-world
        image: 172.30.1.1:5000/myproject/node-hello-world:1.0.2
        resources:
          limits:
            cpu: "0.05"
            memory: "128Mi"
