apiVersion: v1
kind: Service
metadata:
  name: deputybe
spec:
  selector:
    app: deputybe
  ports:
  - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deputybe
spec:
  selector:
    matchLabels:
      app: deputybe
  template:
    metadata:
      labels:
        app: deputybe
    spec:
      containers:
      - name: deputybe
        image: 172.30.1.1:5000/myproject/deputybe:latest
        env:
        - name: POSTGRESQL_URL
          value: "postgres://deputy-database.myproject.svc:5432/deputy?sslmode=disable"
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: deputy-database-credentials
              key: username
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: deputy-database-credentials
              key: password
        resources:
          limits:
            cpu: "0.1"
            memory: "128Mi"
