apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgmatch
spec:
  selector:
    matchLabels:
      app: imgmatch
  template:
    metadata:
      labels:
        app: imgmatch
    spec:
      containers:
      - name: imgmatch
        image: 172.30.1.1:5000/myproject/imgmatch:latest
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: REGISTRY_BASE_URL
          value: "http://openshift-container-registry.myproject.svc:5000"
        - name: POSTGRESQL_URL
          value: "postgres://deputy-database.myproject.svc:5432/deputy?sslmode=disable"
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: deputy-database-credentials
              key: username
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: deputy-database-credentials
              key: password
        resources:
          limits:
            cpu: "0.1"
            memory: "128Mi"
