apiVersion: v1
kind: Service
metadata:
  name: rthook
spec:
  selector:
    app: rthook
  ports:
  - port: 8080
    targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rthook
spec:
  selector:
    matchLabels:
      app: rthook
  template:
    metadata:
      labels:
        app: rthook
    spec:
      containers:
      - name: rthook
        image: 172.30.1.1:5000/myproject/rthook:latest
        env:
        - name: ARTIFACTORY_BASE_URI
          value: "http://mocktifactory.myproject.svc:8091/libs-release-local"
        - name: POSTGRESQL_URL
          value: "postgres://deputy-database.myproject.svc:5432/deputy?sslmode=disable"
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: deputy-database-credentials
              key: username
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: deputy-database-credentials
              key: password
        resources:
          limits:
            cpu: "0.1"
            memory: "128Mi"
