apiVersion: v1
kind: Service
metadata:
  name: tasks-server
spec:
  selector:
    app: tasks-server
  ports:
  - port: 8080
    targetPort: 8877
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-server
spec:
  selector:
    matchLabels:
      app: tasks-server
  template:
    metadata:
      labels:
        app: tasks-server
    spec:
      containers:
      - name: tasks-server
        image: 172.30.1.1:5000/myproject/tasks-server:latest
        command: ["/app/tasks-server"]
        args: ["--server"]
        env:
        - name: ARTIFACTORY_BASE_URI
          value: "http://mocktifactory.myproject.svc:8091/libs-release-local"
        - name: POSTGRESQL_URL
          value: "postgres://deputy-database.myproject.svc:5432/deputy?sslmode=disable"
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: deputy-database-credentials
              key: username
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: deputy-database-credentials
              key: password
        resources:
          limits:
            cpu: "0.1"
            memory: "128Mi"
