apiVersion: v1
kind: Service
metadata:
  name: deputy-database
  labels:
    app: deputy-database
spec:
  selector:
    app: deputy-database
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  sessionAffinity: None
