apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-frontend
spec:
  selector:
    matchLabels:
      app: example-frontend
  template:
    metadata:
      labels:
        app: example-frontend
    spec:
      containers:
      - name: example-frontend
        image: 172.30.1.1:5000/myproject/node-hello-world:1.0.3
        resources:
          limits:
            cpu: "0.05"
            memory: "128Mi"
